### ISSUE TITLE
Dependency on puppet-augeasproviders_core

### ISSUE THREAD

**Issue by samuraiii** [voxpupuli/puppet-augeasproviders_sysctl#70]
Hi it would be nice to fix the dependency of the module from `herculesteam-augeasproviders_core` to `herculesteam-augeasproviders_core` on puppetforge.
Thank you
S

**Comment by bitvijays** [comment]
Hello @Voxpupli Team, Hope you are doing well. Thank you for your continuous support. Facing the same issue. Updating the dependency from `herculesteam-augeasproviders_core` to [puppet-augeasproviders_core](https://github.com/voxpupuli/puppet-augeasproviders_core)

**Comment by JCW-USDA** [comment]
I created my own branch of code and changed the dependency in the metadata file from herculesteam/augeasproviders_core to puppet/augeasproviders_core.  This re-naming has caused many headaches, I would hope there would be consistency with these modules so we can keep them mirrored

**Comment by abegosum** [comment]
As we are cleaning up for upgrades, we came across this problem as well. Would love to see a new Forge version with the proper dependencies.  Thanks for taking this over.
